// PostList
export const POSTLIST_REQUEST = 'POSTLIST_REQUEST';
export const POSTLIST_FAILURE = 'POSTLIST_FAILURE';
export const POSTLIST_SUCCESS = 'POSTLIST_SUCCESS';

// Single Post
export const POST_LOADING = 'POST_LOADING';
export const POST_FAILURE = 'POST_FAILURE';
export const POST_SUCCESS = 'POST_SUCCESS';
