// PostList
export const FETCH_POSTLIST_REQUEST = 'FETCH_POSTLIST_REQUEST';
export const FETCH_POSTLIST_FAILURE = 'FETCH_POSTLIST_FAILURE';
export const FETCH_POSTLIST_SUCCESS = 'FETCH_POSTLIST_SUCCESS';

// Single Post
export const POST_LOADING = 'POST_LOADING';
export const POST_FAILURE = 'POST_FAILURE';
export const POST_SUCCESS = 'POST_SUCCESS';
